apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  namespace: node-app

spec:
  containers:
    - name: node-container
      image: soma1999/node-app-image
      ports:
        - containerPort: 8000
